name: Node CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  summarize:
    name: Generate API, README
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Generate files
        run: node scripts/summarize.mjs run
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Generate API and README summary [skip ci]"
          commit_user_name: FindingAnand
          commit_user_email: bot@anandchowdhary.com
          commit_author: FindingAnand <bot@anandchowdhary.com>
      - name: Dispatch AnandChowdhary/everything update
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          repo: AnandChowdhary/everything
          workflow: api.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
